### PR TITLE
Answer legislation questions

### PR DESCRIPTION
**Pull request by amaia**
Implements #27

### CODE REVIEW

**Comment by ferblape** [comment]
@amaia, @furilo should we check if the debate phase has already finished to don't allow people ro reply?

**Comment by amaia** [comment]
@ferblape yes, I forgot about that, I'll add the check

**Comment by ferblape** [comment]
Given the end date, I'd check including that date. For instance, if the debate ends the 28th of Dec, I'd let people reply until 28th Dec, 23:59:59h

**Comment by ferblape** [comment]
The rest of the PR is ok to me. When we integrate the final HTML we may consider not rendering a replied question options with a form to an update action, but it's a minor detail.

👍

**Pull request merged**
