### PR TITLE
Draft Version page

### PR DESCRIPTION
**Pull request by amaia**
Implements #13 

The adaptation of the css and js to the table of contents (index) made with lists will be done in another issue, after having the annotations part working and the final html for the body of the text.

### CODE REVIEW

**Comment by ferblape** [comment]
Looks great!

Just a small detail: if you see the changes of a version without changes specified, the Redcarpet raises an exception.

```
Showing /Users/fernando/proyectos/consul-legislation/app/views/legislation/draft_versions/changes.html.erb where line #28 raised:

wrong argument type nil (expected String)

app/helpers/application_helper.rb:36:in `render'
app/helpers/application_helper.rb:36:in `markdown'
app/views/legislation/draft_versions/changes.html.erb:28:in `_app_views_legislation_draft_versions_changes_html_erb__1636251233055095561_70315191874680'
```

**Comment by amaia** [comment]
@ferblape thanks! Fixin' it. 
I also forgot to do the preview thing for admins, to show only published versions for normal users and to check dates, so I'll do that too.

**Comment by ferblape** [comment]
Now, as an anonymous user I can see the versions listed: 

screen shot 2017-01-04 at 08 55 35

But I can't access them because they are not published. 

And, as an admin user, if I visit a not published draft, in the dropdown I can't see which is the current version:

screen shot 2017-01-04 at 08 59 31

Maybe, we could add to the name of the version a suffix such as "(en borrador)" for the admins, for not published drafts.

**Comment by amaia** [comment]
@ferblape it should be fixed now

I've left out checking dates, I'll do it in another issue.

About having "(en borrador)" for the admin, I've added an "*" instead, what do you think?

**Comment by ferblape** [comment]
I like the *.

👏 thank you! now works perfectly

**Pull request merged**
