### PR TITLE
Integrate admin html and css from sandbox

### PR DESCRIPTION
**Pull request by amaia**
Implements #42 

The link to Preview for DraftVersion doesn't go anywhere yet, I'll do it as part of #13

### CODE REVIEW

**Comment by ferblape** [comment]
Almost there! I found a few things, not a big deal:

- [ ] legislations home page filters look different in the sandbox
- [ ] legislation link "more information / context" is not integrated yet. If you plan to do it in another issue, just ignore this coment.
- [ ] page title of the legislation home page. It's a small detail, but we should show a proper title

**Comment by amaia** [comment]
@ferblape it should be fixed now

**Comment by ferblape** [comment]
@amaia I still see the filters disorganized:

screen shot 2017-01-02 at 10 37 58

**Comment by amaia** [comment]
@ferblape ah, sorry, I thought you meant inside the admin part, the ones in the public process list are different because I used an existing method in consul to render them, and the css needs to be adjusted by @martgnz

**Comment by martgnz** [comment]
The filters should look OK now 🚀

**Comment by amaia** [comment]
@martgnz thanks!!

**Comment by ferblape** [comment]
👍

**Pull request merged**
